spring:
  application:
    name: bugboard
  datasource:
    url: jdbc:postgresql://db.omxudfheszyemlfdrkyo.supabase.co:5432/postgres?sslmode=require
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8082
