name: Users Sonar Analysis

on:
  push:
    branches: ["main"]
    paths:
      - "backend/users/**"
      - ".github/workflows/sonar-users.yaml"

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Build backend
        working-directory: backend/users
        run: mvn -DskipTests compile

      - name: Debug Sonar env
        run: |
          echo "HOST = '${SONAR_HOST_URL}'"
          echo "TOKEN SET = ${{ secrets.SONAR_TOKEN != '' }}"

      - name: Sonar scan
        uses: SonarSource/sonarqube-scan-action@v7
        with:
          projectBaseDir: backend/users
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
